### PR TITLE
Make JobHandle pure struct for stackalloc compatibility

### LINKED ISSUE #31: Cannot `stackalloc JobHandle[]`
Even though JobHandle is a struct, I cannot seem to be allowed to stackalloc an array of them, which makes allocation free scheduling of jobs from within a loop of unknown runtime count very cumbersome (borderline impossible).

It would be extremely convenient to be able to do this to get the ability to directly and synchronously schedule and then complete workloads without allocating or messing around with a List<JobHandle> or something like that.

It would also help to combine job dependencies as these jobs are being scheduled in parallel. As far as the package's api goes, that requires some sort of Span to be passed in. But assembling that span in memory is impossible without going through another type like System.Array or System.Collections.Generic.List<JobHandle>.

image

... but it is a struct. And that totally works with other structs:

image

What am I getting wrong here? :)

I tried to work with a list with pre-reserved capacity, but I can't even submit a List to Scheduler.CombineDependencies. So there's no chance (without juggling array indices and counting jobs?) to track dependencies as they accrue?
image

### PR DESCRIPTION
**Pull request by LilithSilver**
Resolves #31 by adding a caching system to associate Job and Scheduler classes to a JobHandle that just stores integer IDs.

Ran a few benchmarks; no significant performance impact; it only has to do a couple extra dictionary/array lookups per Schedule and Complete call.

### CODE REVIEW

File: JobScheduler/JobHandle.cs [hunk 1]
```diff
@@ -8,36 +8,138 @@ namespace Schedulers;
...
+    ///     Assigns schedulers an ID, and a cache of tracked jobs.
+    ///     This way, we can store a Scheduler and a Job on a JobHandle by integer ID,
+    ///     so that stackalloc JobHandle[] can work. Otherwise the managed types would prevent it.
+    /// </summary>
+    // A dictionary is OK because we only add when we initialize a new scheduler.
+    // It otherwise doesn't use memory.
+    // Accesses could be sliiiightly faster if we used an array and recycled IDs but not appreciably so,
+    // particularly for the overhead it would involve.
+    private static readonly Dictionary<int, (JobScheduler Scheduler, Job[] JobIds)>
+        _schedulerCache = [];
```
Comment (genaray) [inline JobScheduler/JobHandle.cs:21]: Yep thats right. Im fine here with a dictionary. Just wondering how fast or slow it would be to use an array instead ^^ But that's not a high priority here.

**Review by genaray — APPROVED** [review]
